const mongoose=require('mongoose')
const Schema=mongoose.Schema

const schemaSapWfm=new Schema({
    Muhatap:{type:String},
    Kayittrh_:{type:String},
    Tur:{type:String}, 
    BOaktivitetu_tnm_:{type:String},
    Arizab_t_:{type:String},
    ArizaAltkodutanimi:{type:String},
    Nedenmetni:{type:String}, 
    Siparis:{type:String},
    Arizabsl_:{type:String},
    Arz_bsl_:{type:String},
    Hrk_bas_tr:{type:String},
    Hrk_bas_st:{type:String},
    HareketBslTrhSaat:{type:String},
    Cls_bas_:{type:String},
    Cls_bit_:{type:String},
    CalismaBitis:{type:String},
    Dns_bsl_s_:{type:String},
    Yolsuresi:{type:String},
    Clsmasur_:{type:String}, 
    Dns_suresi:{type:String},
    Teyitveren:{type:String},
    GercekEkipKodlari:{type:String},
    EkipIsimleri:{type:String},
    IlkIsSaati:{type:String},
    IsBitisSaati:{type:String},
    IkiIsArasiSure:{type:String}, 
    Isyeri:{type:String},
    IslemKodu:{type:String},
    Aciklama:{type:String},
    Anah_e_1:{type:String}, 
    DpYr:{type:String}, 
    Plaka:{type:String},
    Hes_nedeni:{type:String}, 
    Kesmetar_:{type:String},
    Kesmesaat:{type:String},
    KesongBi:{type:String},
    Kesintion:{type:String},
    HHEnerjiTrh:{type:String},
    HHEnerjiSaat:{type:String},
    BIldirimSayisi:{type:String},
    BIldirimID:{type:String}, 
    BIldirimAciklmasi:{type:String}, 
    OmsID:{type:String},
    KullanilanMalzemeler:{type:String},
    KullanilanMalzemeAdetleri:{type:String}, 
    KullanilanMalzemeTutarlari_TL_:{type:String}, 
    Isim:{type:String},
})

const SchemaSapWfm=mongoose.model('SchemaSapWfm',schemaSapWfm)
module.exports=SchemaSapWfm